### ISSUE TITLE
大佬，最近从2021.6.6升级到8.8，radio不能用了，求助。

### ISSUE THREAD

**Issue by yuyuye84** [ha0y/xiaomi_gateway_radio#1]
**log如下：**

> Error setting up integration media_player - received exception
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1069, in async_forward_entry_setup
>     result = await async_setup_component(self.hass, domain, self._hass_config)
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 92, in async_setup_component
>     return await setup_tasks[domain]  # type: ignore
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1069, in async_forward_entry_setup
>     result = await async_setup_component(self.hass, domain, self._hass_config)
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 92, in async_setup_component
>     return await setup_tasks[domain]  # type: ignore
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1069, in async_forward_entry_setup
>     result = await async_setup_component(self.hass, domain, self._hass_config)
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 92, in async_setup_component
>     return await setup_tasks[domain]  # type: ignore
>   File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1069, in async_forward_entry_setup
>     result = await async_setup_component(self.hass, domain, self._hass_config)
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 92, in async_setup_component
>     return await setup_tasks[domain]  # type: ignore
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 99, in async_setup_component
>     return await task  # type: ignore
>   File "/usr/src/homeassistant/homeassistant/setup.py", line 209, in _async_setup_component
>     processed_config = await conf_util.async_process_component_config(
>   File "/usr/src/homeassistant/homeassistant/config.py", line 872, in async_process_component_config
>     platform = p_integration.get_platform(domain)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 498, in get_platform
>     cache[full_name] = self._import_platform(platform_name)
>   File "/usr/src/homeassistant/homeassistant/loader.py", line 503, in _import_platform
>     return importlib.import_module(f"{self.pkg_path}.{platform_name}")
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/config/custom_components/xiaomi_gateway_radio/media_player.py", line 35, in <module>
>     SCAN_INTERVAL = timedelta(seconds=10)
> NameError: name 'timedelta' is not defined

**Comment by ha0y** [comment]
已修复。
